name: Coded Clique
description: 'Coded Clique'
branding:
  icon: 'target'
  color: 'purple'

inputs:
  token:
    description: GITHUB_TOKEN
    required: true
  encoding:
    description: 'The encoding method to use: "base64" or "question". Default is "base64".'
    required: false
    default: 'base64'
runs:
  using: 'composite'
  steps:
    - name: Get body based on event type
      id: get-body
      run: |
        if [ "${{ github.event_name }}" == "issues" ]; then
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo ${{ github.event.issue.updated_at }}  >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "issue_comment" ]; then
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo ${{ github.event.comment.updated_at }}  >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        else
          echo "Unsupported event type: ${{ github.event_name }}"
          exit 1
        fi
      shell: bash
    - name: Encode body
      id: encode-body
      run: |
        if [ "${{ inputs.encoding }}" == "base64" ]; then
          echo "body=$(echo -n "${{ steps.get-body.outputs.body }}" | base64 --wrap=0)" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.encoding }}" == "question" ]; then
          # Define an array of conversation starters
          sentences=("So, what have you been up to lately?" "Do you have any plans for the weekend?" "What do you like to do in your free time?" "Have you seen any good movies or TV shows lately?" "What kind of music do you like?" "Have you traveled anywhere interesting recently?" "What is your favorite book or author?" "Do you have any pets?" "What is your favorite thing about your job/school/hobby?" "What do you like to do for fun?")

          # Get a random index from the array
          random_index=$(( RANDOM % ${#sentences[@]} ))

          # Get the sentence at the random index
          random_sentence=${sentences[$random_index]}
          echo "body=$random_sentence" >> $GITHUB_OUTPUT
        else
          echo "Invalid encoding method specified: ${{ inputs.encoding }}"
          exit 1
        fi
      shell: bash
    - name: Update Issue Content
      uses: actions-cool/issues-helper@v2
      with:
        actions: 'update-issue'
        token: ${{ inputs.token }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          <details>
          <summary>${{ steps.encode-body.outputs.body }}

          █▀▀ █▀█ █▀▄ █▀▀ █▀▄   █▀▀ █░░ █ █▀█ █░█ █▀▀
          █▄▄ █▄█ █▄▀ ██▄ █▄▀   █▄▄ █▄▄ █ ▀▀█ █▄█ ██▄
          </summary>

          ---

          ${{ github.event.issue.body }}

          </details>
      if: github.event_name == 'issues'
    - name: Update Comment Content
      uses: actions-cool/issues-helper@v2
      with:
        actions: 'update-comment'
        token: ${{ inputs.token }}
        comment-id: ${{ github.event.comment.id }}
        body: |
          <details>
          <summary> ${{ steps.encode-body.outputs.body }}

          █▀▀ █▀█ █▀▄ █▀▀ █▀▄   █▀▀ █░░ █ █▀█ █░█ █▀▀
          █▄▄ █▄█ █▄▀ ██▄ █▄▀   █▄▄ █▄▄ █ ▀▀█ █▄█ ██▄
          </summary>

          ---

          ${{ github.event.comment.body }}

          </details>
      if: github.event_name == 'issue_comment'
