name: Coded Clique
description: 'Coded Clique'
branding:
  icon: 'target'
  color: 'purple'

inputs:
  token:
    description: GITHUB_TOKEN
    required: true
  encoding:
    description: 'The encoding method to use: "base64" or "rot13". Default is "base64".'
    required: false
    default: 'base64'
runs:
  using: 'composite'
  steps:
    - name: Get issue body
      id: get-issue
      run: |
        echo "body=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Get comment body
      id: get-comment
      run: |
        echo "Event: $(echo '${{ toJSON(github.event) }}' | jq -c '.')"
        echo "body=${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Encode body
      id: encode-body
      run: |
        if [ "${{ inputs.encoding }}" == "base64" ]; then
          echo "body=$(echo -n ${{ steps.get-issue.outputs.body }} | base64 --wrap=0)" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.encoding }}" == "rot13" ]; then
          echo "body=$(echo -n ${{ steps.get-issue.outputs.body }} | tr 'A-Za-z' 'N-ZA-Mn-za-m')" >> $GITHUB_OUTPUT
        else
          echo "Invalid encoding method specified: ${{ inputs.encoding }}"
          exit 1
        fi
      shell: bash
    - name: Echo body content
      run: |
        echo "Body content: ${{ steps.encode-body.outputs.body }}"
      shell: bash
    - name: Update Issue Content
      run: |
        curl \
          -X PATCH \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          ${{ github.event.issue.url }} \
          -d '{"body":"${{ steps.encode-body.outputs.body }}"}'
      shell: bash
