name: Coded Clique
description: 'Coded Clique'
branding:
  icon: 'target'
  color: 'purple'

inputs:
  token:
    description: GITHUB_TOKEN
    required: true
  encoding:
    description: 'The encoding method to use: "base64" or "rot13". Default is "base64".'
    required: false
    default: 'base64'
runs:
  using: 'composite'
  steps:
    - name: Get body based on event type
      id: get-body
      run: |
        if [ "${{ github.event_name }}" == "issue" ]; then
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo "${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "issue_comment" ]; then
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo "${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        else
          echo "Unsupported event type: ${{ github.event_name }}"
          exit 1
        fi
      shell: bash
    - name: Encode body
      id: encode-body
      run: |
        if [ "${{ inputs.encoding }}" == "base64" ]; then
          echo "body=$(echo -n "${{ steps.get-body.outputs.body }}" | base64 --wrap=0)" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.encoding }}" == "rot13" ]; then
          echo "body=$(echo -n "${{ steps.get-body.outputs.body }}" | tr 'A-Za-z' 'N-ZA-Mn-za-m')" >> $GITHUB_OUTPUT
        else
          echo "Invalid encoding method specified: ${{ inputs.encoding }}"
          exit 1
        fi
      shell: bash
    - name: Wrap body in HTML code
      id: wrap-body
      run: |
        echo 'body<<EOF' >> $GITHUB_OUTPUT
        echo "<details>" >> $GITHUB_OUTPUT
        echo "  <summary>❰ ██ ◗ █☰ ◗  ❰ ▙▄ █ █▙ ▙▟ ☰${{ steps.encode-body.outputs.body }}</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "${{ steps.get-body.outputs.body }}" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash
    - name: Echo body content
      run: |
        echo "Body content: ${{ steps.wrap-body.outputs.body }}"
      shell: bash
    - name: Update Issue Content
      run: |
        escaped_body="$(echo "${{ steps.wrap-body.outputs.body }}" | jq -sR .)"
        echo "Escaped body: $escaped_body"
        curl \
          -X PATCH \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          ${{ github.event.issue.url }} \
          -d "{\"body\": $escaped_body }"
      shell: bash
      if: github.event_name == 'issue'
    - name: Update Comment Content
      run: |
        escaped_body="$(echo "${{ steps.wrap-body.outputs.body }}" | jq -sR .)"
        echo "Escaped body: $escaped_body"
        curl \
          -X PATCH \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          ${{ github.event.comment.url }} \
          -d "{\"body\": $escaped_body }"
      shell: bash
      if: github.event_name == 'issue_comment'
